site_name: PyNet Intelligence Documentation
theme:
  name: readthedocs
nav:
    - Overview: index.md
    - User Guide: user_guide.md
    - Pipeline: pipeline.md
    - Policy and Disclaimer: policy.md
    - About the Author: about_the_author.md
